ithds/apps/goods/urls.py
from apps.goods.views import IndexView, ArticleDetailsView
from django.conf.urls import  url


urlpatterns = [
    url(r'^detail/(?P<aricle_id>\d+)$', ArticleDetailsView.as_view(), name='detail'),
    url(r'^', IndexView.as_view(), name='index'),

]

ithds/apps/user/urls.py
from apps.user.views import SignupView, ActiveView, LoginView, UserCenterView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf.urls import url


urlpatterns = [
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^signup$', SignupView.as_view(), name='signup'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    url(r'^homepage$', login_required(UserCenterView.as_view()), name='usercenter')
]

ithds/ithds/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
    url(r'^', include('apps.goods.urls', namespace='goods'))
]

ithds/apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField

# Create your models here.

class Article(BaseModel):
    '''文章模型类'''
    status_choices = (
        (0, '上线'),
        (1, '下线'),
    )

    title = models.CharField(max_length=200, verbose_name='文章标题')
    slug = models.CharField(max_length=200, verbose_name='文章概括')
    text = HTMLField(verbose_name='文章内容')
    status = models.SmallIntegerField(default=0, choices=status_choices, verbose_name='文章状态')
    image = models.ImageField(upload_to='image')

    def __str__(self):

        return  self.title

    class Meta:
        db_table = 'it_article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name

ithds/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel

# Create your models here.

class User(AbstractUser, BaseModel):
    '''用户模型类'''

    class Meta:
        db_table = 'it_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class UserCenter(BaseModel):
    '''用户中心'''
    user = models.ForeignKey('User', verbose_name='所属账户')
    user_exp = models.IntegerField(default=0, verbose_name='用户经验值')
    user_lv = models.SmallIntegerField(default=0, verbose_name='用户等级')
    user_ach = models.CharField(max_length=20, verbose_name='用户成就')


    class Meta:
        db_table = 'it_usercenter'
        verbose_name = '用户中心'
        verbose_name_plural = verbose_name

ithds/apps/goods/views.py
from django.shortcuts import render
from apps.user.models import User
from django.views.generic import View
from apps.goods.models import Article
from django_redis import get_redis_connection



# Create your views here.


class IndexView(View):
    '''首页'''

    def get(self, request):

        aricle = Article.objects.all()
        new_aricle = Article.objects.all().order_by('-create_time')

        return render(request, 'index.html', {'aricle':aricle, 'new_aricle':new_aricle})



class ArticleDetailsView(View):
    '''文章详情页'''

    def get(self, request, aricle_id):

        user = request.user

        print(user.username)

        # 最新发布
        new_aricle = Article.objects.all().order_by('-create_time')

        # 相关推荐
        recommend_aricle = Article.objects.all()

        # 文章主体
        aricle = Article.objects.get(id=aricle_id)

        if user.is_authenticated():
            # 判断用户是否登录
            # 添加历史浏览记录
            conn = get_redis_connection('default')
            history_key = 'history_%d' %user.id
            # 移除 aricle.id
            conn.lrem(history_key, 0, aricle.id)
            # 从左侧插入
            conn.lpush(history_key, aricle.id)
            # 显示 最新 的 5条 ltrim 进行裁切
            conn.ltrim(history_key, 0, 4)


        # 整理上下文
        context = {'aricle':aricle, 'new_aricle':new_aricle, 'recommend':recommend_aricle}



        return render(request, 'detail.html', context)

ithds/apps/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from celery_tasks.tasks import send_signup_active_email
from django.contrib.auth import authenticate, login, logout
from django_redis import get_redis_connection
from apps.goods.models import Article

from django.contrib.auth.decorators import login_required


from django.conf import settings
from django.views.generic import View
from apps.user.models import User
import re


# Create your views here.

class SignupView(View):

    def get(self, request):
        print('get')

        return render(request, 'signup.html')

    def post(self, request):

        username = request.POST.get('username')
        password = request.POST.get('pwd')
        repassword = request.POST.get('repwd')
        email = request.POST.get('email')

        # 检验信息是否填写完整
        if not all([username, password, email]):

            return render(request, 'signup.html', {'errmsg': '数据填写不完整'})

        # 判断 两次密码是否输入 相同
        if not password == repassword:

            return render(request, 'signup.html', {'errmsg': '两次密码输入不相同'})

        # 检验邮箱格式是否合法
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):

            return render(request, 'signup.html', {'errmsg': '邮箱格式不合法'})

        # 检验用户名是否重复
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            # 用户名不存在
            user = None
        if user:
            # 用户名已存在
            return render(request, 'signup.html', {'errmsg': '用户名已存在'})

        # 进行业务处理 : 进行用户注册
        # 把校验完的数据 添加到 表里面
        user = User.objects.create_user(username, email, password)
        user.is_active = 0
        user.save()

        # 加密用户身份信息
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'confirm': user.id}
        token = serializer.dumps(info)  # bytes
        token = token.decode()

        # 发送用户激活邮件
        send_signup_active_email.delay(email, username, token)

        return redirect(reverse('goods:index'))


class ActiveView(View):
    '''用户激活'''
    def get(self, request, token):
        '''进行用户激活'''

        # 进行解密 获取加密的用户信息
        serializer = Serializer(settings.SECRET_KEY, 3600)
        try:
            info = serializer.loads(token)
            userid = info['confirm']
            # 根据 id获取用户信息
            user = User.objects.get(id=userid)
            user.is_active = 1  # 修改用户激活状态
            user.save()

            # 跳转到登录页面
            return redirect (reverse('user:login'))

        except SignatureExpired as e:
            # 激活链接  已经过期
            return HttpResponse('激活链接已经过期')


class LoginView(View):
    '''登录'''

    def get(self, request):

        return render(request, 'login.html')

    def post(self, request):
        '''登录检验'''

        # 接受数据

        username = request.POST.get('username')
        password = request.POST.get('pwd')

        # 校验数据完整性
        if not all([username, password]):
            print(username, password)
            return render(request, 'login.html', {'errmsg':'数据填写不完整'})

        # 判断用户名密码
        user = authenticate(username=username, password=password)
        if user is not None:
            # 用户名密码正确
            if user.is_active:
                # 用户已激活
                # 记录用户登录状态
                login(request, user)

                # 获取登录后要跳转的页面
                next_rul = request.GET.get('next', reverse('goods:index'))

                # 跳转到首页
                return redirect(next_rul)

            else:
                return render(request, 'login.html', {'errmsg':'用户未激活'})

        else:
            return render(request, 'login.html', {'errmsg':'用户名或密码错误'})


# user/logout
class LogoutView(View):
    '''退出登录'''

    def get(self, request):
        # 清除 session 信息
        logout(request)
        # 跳转到首页
        return redirect(reverse('goods:index'))


class UserCenterView(View):
    '''用户中心'''

    def get(self, request):
        '''显示'''


        user = request.user

        user = User.objects.get(id=user.id)

        # 获取用户的浏览记录
        conn = get_redis_connection('default')

        history_key = 'history_%d'%user.id

        # 获取用户最新浏览的文章id
        aricle_ids = conn.lrange(history_key, 0, 4)

        # aricle_list = Article.objects.filter(id__in=aricle_ids)
        #
        # print(len(aricle_list))

        aricle_list = []

        for aricle_id in aricle_ids:
            aricle = Article.objects.get(id=aricle_id)
            aricle_list.append(aricle)




        return render(request, 'homepage.html', {'user':user, 'aricle_list':aricle_list})

ithds/templates/detail.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>新闻详情</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'goods:index' %}"></a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li><a href="#">新闻</a></li>
				<li><a href="#">体育</a></li>
				<li><a href="#">娱乐</a></li>
			</ul>
            {% if user.is_authenticated %}
                <div class="usercenter">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:usercenter' %}">用户中心</a></li>
                        <li><a href="{% url 'user:logout' %}">退出用户</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="register">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:login' %}">登录</a></li>
                        <li><a href="{% url 'user:signup' %}">注册</a></li>
                    </ul>
                </div>
            {% endif %}
	    </div>
	</div>
	<div class="container">
		<div class="col-md-8">
			<h1 class="news-title">{{ aricle.title }}</h1>
			<div class="news-status">{{ aricle.create_time }}发布
				<div class="label label-warning">情感</div>
     			<div class="label label-default">教育</div>
			</div>
			<div class="content">
				<blockquote>
					<p>{{ aricle.slug }}</p>
				</blockquote>
				<div>
				</div>
				<img src="{% static aricle.image %}" alt="">
                {%autoescape off%}
                {{ aricle.text }}
                {% endautoescape %}
            </div>
		</div>
		<div class="col-md-4">
            
            <div class="side-bar-card">
            	<div class="card-title">相关推荐</div>
            	<div class="card-body ">
            		<div class="list">

                        {% for aricle in recommend %}
                            <div class="item clearfix">
                                <div class="col-xs-5 no-padding-h">
                                    <img src="{% static aricle.image %}">
                                </div>
                                <div class="col-xs-7">
                                    <a href="{% url 'goods:detail' aricle.id %}"class="title">{{ aricle.title }}</a>
                                    <div class="desc">{{ aricle.create_time }} 发布</div>
                                </div>
                            </div>
                        {% endfor %}

            		</div>
            	</div>
            </div>
            	<div class="side-bar-card">
					<div class="card-title">今日最新</div>
					<div class="card-body">
						<div class="list">

							{% for aricle in new_aricle %}
                                <div class="item">
                                    <a href="{% url 'goods:detail' aricle.id %}"class="title">{{ aricle.title }}</a>
                                    <div class="desc">{{ aricle.create }}</div>
                                </div>
                            {% endfor %}
						</div>
					</div>
				</div>
		</div>
	</div>
	
	<div class="footer">
		<p>© 2019 拴蛋头条 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公网安备
		</p>
    </div>

</body>
</html>

ithds/templates/homepage.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>密云头条</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="index.html"></a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="index.html">首页</a></li>
				<li><a href="#">新闻</a></li>
				<li><a href="#">体育</a></li>
				<li><a href="#">娱乐</a></li>
			</ul>
            {% if user.is_authenticated %}
                <div class="usercenter">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="{% url 'user:usercenter' %}">用户中心</a></li>
                        <li><a href="{% url 'user:logout' %}">退出用户</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="register">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:login' %}">登录</a></li>
                        <li><a href="{% url 'user:signup' %}">注册</a></li>
                    </ul>
                </div>
            {% endif %}
	    </div>
	</div>
		<div class="container">
		    <div class="row">
				<div class="col-sm-3">
					<div class="list-group side-bar">
						<a href="#" class="list-group-item active">个人资料</a>
					</div>
				</div>
				<div class="col-sm-9">
					<div class="info-list clearfix">
						<div class="col-xs-4">
							<div class="side-bar-card flag clearfix">
								<div class="col-xs-3">
									<img src="{% static 'image/007.png' %}" alt="等级">
								</div>
								<div class="col-xs-9">
									<div class="text-lg">Lv.19</div>
									<div>经验值1330</div>
								</div>
						    </div>
						</div>
						<div class="col-xs-4">
							<div class="side-bar-card flag clearfix">
								<div class="col-xs-3">
									<img src="{% static 'image/006.png' %}" alt="金币">
								</div>
								<div class="col-xs-9">
									<div class="text-lg">我的金币</div>
									<div>1050金币</div>
								</div>
						    </div>
						</div>
						<div class="col-xs-4">
							<div class="side-bar-card flag clearfix">
								<div class="col-xs-3">
									<img src="{% static 'image/008.png' %}" alt="成就">
								</div>
								<div class="col-xs-9">
									<div class="text-lg">我的成就</div>
									<div>暂无成就</div>
								</div>
						    </div>
						</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
					    		<div class="panel-title">个人资料</div>
					    	</div>
					    	<div class="panel-body">
								<div class="user_info_list">
									<p><span>用户名:</span>{{ user.username }}</p>
		                            <p><span>邮箱:</span>{{ user.email }}</p>
		                            <p><span>注册时间:</span>{{ user.create_time }}</p>
							    </div>
						    </div>
						</div>
					    <div class="panel panel-default">
					    	<div class="panel-heading">
					    		<div class="panel-title">浏览记录</div>
					    	</div>
					    	<div class="panel-body">

                                {% for aricle in aricle_list %}



					    		<div class="new-list-item clearfix">
						    		<div class="col-xs-3">
						    			<img src="{% static aricle.image %}" alt="">
						    		</div>
						    		<div class="col-xs-7">
						    			<a href="{% url 'goods:detail' aricle.id %}" class="title">{{ aricle.title }}</a>
						    		</div>
					    	    </div>
                                 {% endfor %}
{#					    	    <div class="new-list-item clearfix">#}
{#						    		<div class="col-xs-3">#}
{#						    			<img src="image/002.jpg">#}
{#						    		</div>#}
{#						    		<div class="col-xs-7">#}
{#						    			<a href="detail.html" class="title"> 2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉</a>#}
{#						    		</div>#}
{#					    	    </div>#}
{#					    	    <div class="new-list-item clearfix">#}
{#						    		<div class="col-xs-3">#}
{#						    			<img src="image/002.jpg">#}
{#						    		</div>#}
{#						    		<div class="col-xs-7">#}
{#						    			<a href="detail.html" class="title"> 2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉</a>#}
{#						    		</div>#}
{#					    	    </div>#}
{#					    	    <div class="new-list-item clearfix">#}
{#						    		<div class="col-xs-3">#}
{#						    			<img src="image/002.jpg">#}
{#						    		</div>#}
{#						    		<div class="col-xs-7">#}
{#						    			<a href="detail.html" class="title"> 2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉2年前他为教育事业和高圆圆分手，今成这般，高圆圆：我有一句MMP如鲠在喉</a>#}
{#						    		</div>#}
{#					    	    </div>#}
					    	
					        </div>
					    </div>
					
				</div>
	        </div>
        </div>

				
		
			<!-- <form>
				<div class="detail-line">
					<div class="detail-title-item">昵称</div>
					<input type="text" class="form-control" value="username">
				</div>
				<div class="form-group">
					<label>密码</label>
					<input type="password" class="form-control">
				</div>
				<div class="form-group">
					<button class="btn btn-primary btn-block" type="submit" >登录</button>
				</div>
			</form> -->
	

			
		</div>
        </div>
</div>
<div class="footer">
	<p>© 2019 拴拴头条 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公网安备</p>
</div>

</body>
</html>

ithds/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>密云头条</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="index.html"></a>
			</div>
			<ul class="nav navbar-nav">
				<li class=active><a href="{% url 'goods:index' %}">首页</a></li>
				<li><a href="#">新闻</a></li>
				<li><a href="#">体育</a></li>
				<li><a href="#">娱乐</a></li>
			</ul>

            {% if user.is_authenticated %}
                <div class="usercenter">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:usercenter' %}">用户中心</a></li>
                        <li><a href="{% url 'user:logout' %}">退出用户</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="register">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:login' %}">登录</a></li>
                        <li><a href="{% url 'user:signup' %}">注册</a></li>
                    </ul>
                </div>
            {% endif %}
	    </div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<div class="list-group side-bar">
					<a href="#" class="list-group-item active">综合</a>
					<a href="#" class="list-group-item">软件中心</a>
					<a href="#" class="list-group-item">测评中心</a>
					<a href="#" class="list-group-item">手机中心</a>
					<a href="#" class="list-group-item">电脑中心</a>
					<a href="#" class="list-group-item">相机中心</a>
				</div>
			</div>
			<div class="col-sm-7">
				<div class="new-list">

                    {% for foo in aricle %}
                        <div class="new-list-item clearfix">
                            <div class="col-xs-5">
                            <img src="{% static foo.image %}">
                            </div>
                            <div class="cor-xs-7">
                                <a href="{% url 'goods:detail' foo.id%}" class="title">{{ foo.title }}</a>

                                <div class="info">
                                    <span><span class="avatar"><img src="{% static 'image/logo.png' %}"></span>tobi</span>·
                                    <span>{{ foo.create_time }}发布</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
			<div class="col-sm-3">
				<div class="search-bar">
					<input type="search" class="form-control" placeholder="搜索">
				</div>
				<div class="side-bar-card flag clearfix">
					<div class="col-xs-5">
						<img src="{% static 'image/1-1.png' %}" alt="举报">
					</div>
					<div class="col-xs-7">
						<div class="text-lg">有害信息举报专区</div>
						<div>举报电话12377</div>
					</div>
				</div>
				<div class="side-bar-card">
					<div class="card-title">今日最新</div>
					<div class="card-body">
						<div class="list">
                            {% for aricle in new_aricle %}
                                <div class="item">
                                    <a href="{% url 'goods:detail' aricle.id %}"class="title">{{ aricle.title }}</a>
                                    <div class="desc">{{ aricle.create }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<div class="footer">
	<p>© 2019 拴拴头条 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公网安备</p>
</div>

</body>
</html>

ithds/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>密云头条</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="index.html"></a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="#">首页</a></li>
				<li><a href="#">新闻</a></li>
				<li><a href="#">体育</a></li>
				<li><a href="#">娱乐</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><a href="{% url 'user:login' %}">登录</a></li>
				<li><a href="{% url 'user:signup' %}">注册</a></li>
			</ul>
	    </div>
	</div>
	<div class="container container-small">
		<h1>登录
		<small>没有账号？<a href="{% url 'user:signup' %}">注册</a></small>
	    </h1>
		<form method="post">
            {% csrf_token %}
			<div class="form-group">
				<label>用户名/邮箱</label>
				<input type="text" class="form-control" name="username">
			</div>
			<div class="form-group">
				<label>密码</label>
				<input type="password" class="form-control" name="pwd">
			</div>
			<div class="form-group">
				<button class="btn btn-primary btn-block" type="submit" >登录</button>
			</div>
		</form>
        {{ errmsg }}
	
    </div>

<div class="footer">
	<p>© 2019 拴蛋头条 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公网安备</p>
</div>

</body>
</html>

ithds/templates/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>密云头条</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'goods:index' %}"></a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="#">首页</a></li>
				<li><a href="#">新闻</a></li>
				<li><a href="#">体育</a></li>
				<li><a href="#">娱乐</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'user:login' %}">登录</a></li>
				<li class="active"><a href="{% url 'user:signup' %}">注册</a></li>
			</ul>
	    </div>
	</div>
	<div class="container container-small">
		<h1>注册
		<small>已有账号？<a href="{% url 'user:login' %}">登录</a></small>
	    </h1>
		<form method="post">
            {% csrf_token %}
			<div class="form-group">
				<label>用户名</label>
				<input type="text" class="form-control" name="username">
			</div>
			<div class="form-group">
				<label>密码</label>
				<input type="password" class="form-control" name="pwd">
			</div>
			<div class="form-group">
				<label>确认密码</label>
				<input type="password" class="form-control" name="repwd">
			</div>
			<div class="form-group">
				<label>邮箱</label>
				<input type="text" class="form-control" name="email">
			</div>
			<div class="form-group">
				<button class="btn btn-primary btn-block" type="submit" >注册</button>
			</div>
			<div class="form-group">
        注册拴蛋头条即代表您同意<a href="#">拴蛋头条服务条款</a>
            </div>
		</form>
        {{ errmsg }}
	
    </div>

<div class="footer">
	<p>© 2019 拴蛋头条 中国互联网举报中心京ICP证1401号京ICP备125439号-3京公网安备</p>
</div>


</body>
</html>